(define (make-account balance password)
  (let ((wrong-password-count 0))
    (define (withdraw amount)
      (if (>= balance amount)
	  (begin (set! balance (- balance amount))
		 balance)
	  "Insufficient funds"))
    (define (deposit amount)
      (set! balance (+ balance amount))
      balance)

    (define (tell-about-wrong-password _) "Incorrect password!")

    (define (wrong-password? p)
      (if (not (equal? p password))
	  (begin
	    (set! wrong-password-count (+ 1 wrong-password-count))
	    (if (>= wrong-password-count 7) (call-the-cops))
	    #t)
	  #f))
    
    (define (dispatch p m)
      (cond ((wrong-password? p) tell-about-wrong-password)
	    ((eq? m 'withdraw) withdraw)
	    ((eq? m 'deposit) deposit)
	    (else (error "Unknown request" m))))
    dispatch))

(define (call-the-cops)
  (print "I am calling the cops"))
