(define (wrong-password amount) "Incorrect password!")

(define (make-account balance password)
  (define (withdraw amount)
    (if (>= balance amount)
        (begin (set! balance (- balance amount))
               balance)
        "Insufficient funds"))
  (define (deposit amount)
    (set! balance (+ balance amount))
    balance)
  (define (dispatch p m)
    (cond ((not (equal? p password)) wrong-password)
          ((eq? m 'withdraw) withdraw)
          ((eq? m 'deposit) deposit)
          (else (error "Unknown request" m))))
  dispatch)

(define (make-joint account account-password new-password)
  (define (dispatch p m)
    (if (equal? p new-password)
        (account account-password m)
        wrong-password))
  dispatch)
